### ISSUE TITLE
canot find package code.google.com/p/go.image/tiff

### ISSUE THREAD

**Issue by aanelzam93** [verifiedninja/webapp#1]
i can't to find the package ::
cannot find package "code.google.com/p/go.image/bmp" in any of:
cannot find package "code.google.com/p/go.image/tiff" in any of:

any one can help me ?

**Comment by josephspurrier** [comment]
The libraries have been renamed: golang.org/x/image/bmp. I vendored a few of the dependencies since many are out of date. It should be good to go now.

https://github.com/verifiedninja/webapp/commit/c65dae7c1d59e67683140ba4eb8e2211592cb267
