### ISSUE TITLE
A problem in port allocation

### ISSUE THREAD

**Issue by agn-7** [verifiedninja/webapp#3]
When I'm using from the `80` port in the config file, I get this error:

``
2018-12-13 12:11:39 AM Running HTTP :80
server.go:43: listen tcp :80: bind: permission denied
exit status 1
``

**Comment by josephspurrier** [comment]
Some operating systems allow you to use 80 with elevated permissions. You can run with sudo or As Administrator to use port 80 or change the Server.HTTPPort in the config.json file to: 8080.

**Comment by agn-7** [comment]
With `sudo go run webapp.go` command I got this error:
``
sudo: go: command not found
``

---
So, I build it with `go build webapp.go` then run it with `sudo` permission without any problem and CSS loaded correctly:
``
sudo ./webapp
``

**Comment by josephspurrier** [comment]
I'm closing this issue, let me know if you need anything else.
