### ISSUE TITLE
CSS not loaded with other ports

### ISSUE THREAD

**Issue by agn-7** [verifiedninja/webapp#4]
I've got a[ problem](https://github.com/verifiedninja/webapp/issues/3) with using the `80` port, so I decide that using another port with editing the config file like `8000`.

But when I used another port, CSS not loaded, I think this problem reasons, is a routing problem in UI.

**Comment by josephspurrier** [comment]
Yeah, you're correct. I just tried it and got the same problem. It's because the BaseURL and the serving port are different. If you change the View.BaseURI section of the config.json file to "http://localhost:8080/", the CSS should work as expected.

**Comment by agn-7** [comment]
Thanks, it works fine.
